In [338]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset
import torch.nn as nn
import torch.nn.functional as F
from torch.optim.lr_scheduler import ReduceLROnPlateau
import matplotlib.pyplot as plt
import re
from sklearn.decomposition import PCA
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, adjusted_rand_score, confusion_matrix
from sklearn.mixture import GaussianMixture
from sklearn.manifold import TSNE
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score, roc_curve, auc
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score, recall_score
from itertools import product
from sklearn.model_selection import StratifiedKFold
import optuna

In [339]:
frb_data = pd.read_csv('frb-data.csv')
frb_data['Repeater'] = frb_data['Repeater'].map({'Yes': 1, 'No': 0})
frb_data['Repeater'] = frb_data['Repeater'].fillna(0)
frb_data['Repeater'] = frb_data['Repeater'].astype(int)

In [340]:
# Select numerical columns that are relevant for VAE training
# features = ['Observing_band', 'MJD', 'GL', 'GB', 'SNR', 'DM_SNR', 'DM_SNR_err', 'DM_alig', 'DM_alig_err', 'Flux_density', 
#             'Flux_density_err', 'Width', 'Width_err', 'Freq_high', 'Freq_low', 'Freq_peak', 'Fluence', 'Fluence_err', 'Energy', 
#             'Energy_err', 'Polar_l', 'Polar_l_err', 'Polar_c', 'Polar_c_err', 'RM_syn', 'RM_syn_err', 'RM_QUfit', 'RM_QUfit_err', 'Scatt_t', 'Scatt_t_err', 'Scin_f', 'Scin_f_err',]

labels = frb_data['Repeater']

# Function to clean numerical strings and convert to float
def clean_numeric_value(value):
    if isinstance(value, str):
        value = value.strip()
        if not value:
            return np.nan
        try:
            # Remove special characters and split if necessary
            for char in ['/', '+', '<', '>', '~']:
                value = value.replace(char, '')
            if '-' in value:
                value = value.split('-')[0]
            return float(value)
        except ValueError:
            return np.nan
    try:
        return float(value)
    except (ValueError, TypeError):
        return np.nan
    
error_features = [
    'DM_SNR', 'DM_alig', 'Flux_density', 'Width', 'Fluence', 'Energy',
    'Polar_l', 'Polar_c', 'RM_syn', 'RM_QUfit', 'Scatt_t', 'Scin_f'
]
base_features = [
    'Observing_band', 'MJD', 'GL', 'GB', 'SNR', 'Freq_high',
    'Freq_low', 'Freq_peak', 'Repeater'
]

for feature in base_features + error_features:
    frb_data[feature] = frb_data[feature].apply(clean_numeric_value)

for feature in error_features:
    frb_data[f'{feature}_err'] = frb_data[f'{feature}_err'].apply(clean_numeric_value)

for feature in error_features:
    frb_data[f'{feature}_upper'] = frb_data[feature] + frb_data[f'{feature}_err']
    frb_data[f'{feature}_lower'] = frb_data[feature] - frb_data[f'{feature}_err']
    frb_data[f'{feature}_lower'] = frb_data[f'{feature}_lower'].clip(lower=0)

features = (
    base_features +
    error_features +
    [f'{feature}_upper' for feature in error_features] +
    [f'{feature}_lower' for feature in error_features]
)

In [341]:
frb_data_clean = frb_data[features].fillna(0)
scaler = StandardScaler()
frb_data_scaled = scaler.fit_transform(frb_data_clean)

# Retain the original indices
indices = frb_data_clean.index

# Split the data and retain indices
train_data, val_data, train_labels, val_labels, train_indices, val_indices = train_test_split(
    frb_data_scaled, labels, indices, test_size=0.2, random_state=42, stratify=labels
)

# Convert to PyTorch tensors
train_tensor = torch.tensor(train_data, dtype=torch.float32)
val_tensor = torch.tensor(val_data, dtype=torch.float32)
train_labels_tensor = torch.tensor(train_labels.values, dtype=torch.long)
val_labels_tensor = torch.tensor(val_labels.values, dtype=torch.long)

# Create datasets and dataloaders
batch_size = 64
train_dataset = TensorDataset(train_tensor, train_labels_tensor)
val_dataset = TensorDataset(val_tensor, val_labels_tensor)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

In [342]:
class SupervisedVAE(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim, dropout_rate=0.3, activation=nn.LeakyReLU(0.1)):
        super(SupervisedVAE, self).__init__()
        
        self.activation = activation
        
        # Encoder
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            self.activation,
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            self.activation,
            nn.Dropout(dropout_rate)
        )
        
        self.fc_mu = nn.Linear(hidden_dim, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim, latent_dim)
        
        # Decoder
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            self.activation,
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            self.activation,
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_dim, input_dim)
        )
        
        # Classification head for binary classification
        self.classifier = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim // 2),
            self.activation,
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_dim // 2, 1),
            nn.Sigmoid()
        )
    
    def encode(self, x):
        h = self.encoder(x)
        return self.fc_mu(h), self.fc_logvar(h)
    
    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std
    
    def decode(self, z):
        return self.decoder(z)
    
    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        recon_x = self.decode(z)
        class_prob = self.classifier(z)
        return recon_x, mu, logvar, class_prob

In [343]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
input_dim = frb_data_scaled.shape[1]
hidden_dim = 256
latent_dim = 10
patience = 4
num_epochs = 150

In [344]:
reconstruction_loss_fn = nn.MSELoss(reduction='sum')
classification_loss_fn = nn.BCELoss()

def loss_function(recon_x, x, mu, logvar, class_prob, labels, beta, gamma):
    recon_loss = reconstruction_loss_fn(recon_x, x)
    kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    class_loss = classification_loss_fn(class_prob, labels.unsqueeze(1).float())
    total_loss = recon_loss + beta * kl_loss + gamma * class_loss
    return total_loss, recon_loss, kl_loss, class_loss



In [345]:
def train_supervised(model, optimizer, scheduler, epoch, beta, gamma):
    model.train()
    train_loss = 0
    recon_loss_total = 0
    kl_loss_total = 0
    classification_loss_total = 0
    
    correct = 0
    total = 0
    
    for batch_idx, (data, labels) in enumerate(train_loader):
        data, labels = data.to(device), labels.to(device)
        optimizer.zero_grad()
        recon_batch, mu, logvar, class_logits = model(data)
        
        # Supervised loss function
        loss, recon_loss, kl_loss, classification_loss = loss_function(
            recon_batch, data, mu, logvar, class_logits, labels, beta, gamma
        )
        
        loss.backward()
        optimizer.step()
        
        train_loss += loss.item()
        recon_loss_total += recon_loss.item()
        kl_loss_total += kl_loss.item()
        classification_loss_total += classification_loss.item()
        
        predicted = (class_logits > 0.5).float()
        total += labels.size(0)
        correct += (predicted.squeeze() == labels).sum().item()
        
        # if batch_idx % 100 == 0:
        #     print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)} '
        #           f'({100. * batch_idx / len(train_loader):.0f}%)]\tLoss: {loss.item() / len(data):.6f}')
    
    # Calculate average loss and accuracy for the epoch
    avg_loss = train_loss / len(train_loader.dataset)
    avg_recon = recon_loss_total / len(train_loader.dataset)
    avg_kl = kl_loss_total / len(train_loader.dataset)
    avg_class = classification_loss_total / len(train_loader.dataset)
    accuracy = correct / total
    
    # print(f'====> Epoch: {epoch} Average loss: {avg_loss:.4f}, Recon: {avg_recon:.4f}, KL: {avg_kl:.4f}, '
    #       f'Class: {avg_class:.4f}, Accuracy: {accuracy:.4f}')
    return avg_loss, avg_recon, avg_kl, avg_class, accuracy

def validate_supervised(model, scheduler, optimizer, epoch, beta, gamma):
    model.eval()
    val_loss = 0
    recon_loss_total = 0
    kl_loss_total = 0
    classification_loss_total = 0
    correct = 0
    total = 0
    
    with torch.no_grad():
        for data, labels in val_loader:
            data, labels = data.to(device), labels.to(device)
            recon_batch, mu, logvar, class_logits = model(data)
            
            loss, recon_loss, kl_loss, classification_loss = loss_function(
                recon_batch, data, mu, logvar, class_logits, labels, beta, gamma
            )
            
            val_loss += loss.item()
            recon_loss_total += recon_loss.item()
            kl_loss_total += kl_loss.item()
            classification_loss_total += classification_loss.item()
            
            predicted = (class_logits > 0.5).float()
            total += labels.size(0)
            correct += (predicted.squeeze() == labels).sum().item()
    
    avg_loss = val_loss / len(val_loader.dataset)
    avg_recon = recon_loss_total / len(val_loader.dataset)
    avg_kl = kl_loss_total / len(val_loader.dataset)
    avg_class = classification_loss_total / len(val_loader.dataset)
    accuracy = correct / total
    
    # print(f'====> Validation loss: {avg_loss:.4f}, Recon: {avg_recon:.4f}, KL: {avg_kl:.4f}, '
    #       f'Class: {avg_class:.4f}, Accuracy: {accuracy:.4f}')
    return avg_loss, avg_recon, avg_kl, avg_class, accuracy


def early_stopping(val_losses, patience):
    if len(val_losses) > patience:
        if all(val_losses[-i-1] <= val_losses[-i] for i in range(1, patience+1)):
            return True
    return False



In [346]:
def evaluate_classifier(model, dataloader, device):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for data, labels in dataloader:
            data = data.to(device)
            labels = labels.to(device)
            class_logits = model(data)[-1]
            preds = (class_logits > 0.5).float().cpu().numpy().squeeze()
            all_preds.extend(preds)
            all_labels.extend(labels.cpu().numpy())
    
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)
    
    accuracy = accuracy_score(all_labels, all_preds)
    class_report = classification_report(all_labels, all_preds, target_names=["Non-Repeater", "Repeater"])
    conf_matrix = confusion_matrix(all_labels, all_preds)
    recall = recall_score(all_labels, all_preds, average='weighted')

    
    false_positives = np.sum((all_labels == 0) & (all_preds == 1))

    return accuracy, class_report, conf_matrix, recall, false_positives  # Return F1 score as well

def get_activation_function(name):
    if name == 'ReLU':
        return nn.ReLU()
    elif name == 'LeakyReLU':
        return nn.LeakyReLU(0.1)
    elif name == 'ELU':
        return nn.ELU()
    elif name == 'SELU':
        return nn.SELU()
    elif name == 'GELU':
        return nn.GELU()
    else:
        raise ValueError(f"Unknown activation function: {name}")

In [42]:
def evaluate_classifier_full(model, dataloader, device):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for data, labels in dataloader:
            data = data.to(device)
            class_logits = model(data)[-1]
            preds = (class_logits > 0.5).float().cpu().numpy().squeeze()
            all_preds.extend(preds)
            all_labels.extend(labels.cpu().numpy())
    
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)
    
    accuracy = accuracy_score(all_labels, all_preds)
    class_report = classification_report(all_labels, all_preds, target_names=["Non-Repeater", "Repeater"])
    conf_matrix = confusion_matrix(all_labels, all_preds)
    
    return accuracy, class_report, conf_matrix, all_preds, all_labels

original_data = pd.read_csv('frb-data.csv')
original_data['Repeater'] = original_data['Repeater'].map({'Yes': 1, 'No': 0}).fillna(0).astype(int)

In [44]:
garcia_list = '''
FRB20180907E
FRB20180920B
FRB20180928A
FRB20181017B
FRB20181022E
FRB20181125A
FRB20181125A
FRB20181125A
FRB20181214A
FRB20181220A
FRB20181226E
FRB20181229B
FRB20190112A
FRB20190128C
FRB20190206B
FRB20190206A
FRB20190218B
FRB20190223A
FRB20190308C
FRB20190308C
FRB20190323D
FRB20190329A
FRB20190410A
FRB20190412B
FRB20190423B
FRB20190423B
FRB20190429B
FRB20190430A
FRB20190527A
FRB20190527A
FRB20190601C
FRB20190601C
FRB20190617B
FRB20180910A
FRB20190210C
FRB20200726D
'''.split()

luo_list = '''
FRB20181229B
FRB20190423B
FRB20190410A
FRB20181017B
FRB20181128C
FRB20190422A
FRB20190409B
FRB20190329A
FRB20190423B
FRB20190206A
FRB20190128C
FRB20190106A
FRB20190129A
FRB20181030E
FRB20190527A
FRB20190218B
FRB20190609A
FRB20190412B
FRB20190125B
FRB20181231B
FRB20181221A
FRB20190112A
FRB20190125A
FRB20181218C
FRB20190429B
FRB20190109B
FRB20190206B
'''.split()

zhu_ge_list = '''
FRB20180911A
FRB20180915B
FRB20180920B
FRB20180923A
FRB20180923C
FRB20180928A
FRB20181013E
FRB20181017B
FRB20181030E
FRB20181125A
FRB20181125A
FRB20181125A
FRB20181130A
FRB20181214A
FRB20181220A
FRB20181221A
FRB20181226E
FRB20181229B
FRB20181231B
FRB20190106B
FRB20190109B
FRB20190110C
FRB20190111A
FRB20190112A
FRB20190129A
FRB20190204A
FRB20190206A
FRB20190218B
FRB20190220A
FRB20190221A
FRB20190222B
FRB20190223A
FRB20190228A
FRB20190308C
FRB20190308C
FRB20190308B
FRB20190308B
FRB20190323D
FRB20190329A
FRB20190403E
FRB20190409B
FRB20190410A
FRB20190412B
FRB20190418A
FRB20190419A
FRB20190422A
FRB20190422A
FRB20190423A
FRB20190423B
FRB20190423B
FRB20190429B
FRB20190430A
FRB20190517C
FRB20190527A
FRB20190527A
FRB20190531C
FRB20190601B
FRB20190601C
FRB20190601C
FRB20190609A
FRB20190617A
FRB20190617B
FRB20190618A
FRB20190625A
'''.split()

In [310]:
def objective(trial):
    hidden_dim = trial.suggest_int('hidden_dim', 128, 512)
    latent_dim = trial.suggest_int('latent_dim', 5, 20)
    beta = trial.suggest_float('beta', 0.5, 2.0)
    gamma = trial.suggest_float('gamma', 0.5, 2.0)
    dropout_rate = trial.suggest_float('dropout_rate', 0.1, 0.5)
    
    activation_name = trial.suggest_categorical('activation', ['ReLU', 'LeakyReLU', 'ELU', 'SELU', 'GELU'])
    activation = get_activation_function(activation_name)

    model = SupervisedVAE(input_dim, hidden_dim, latent_dim, dropout_rate, activation).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=4)
    
    all_false_positives = []
    all_false_negatives = []
    all_true_positives = []
    all_true_negatives = []

    num_epochs = 50

    n_folds = 5
    skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=42)


    for fold, (train_index, val_index) in enumerate(skf.split(frb_data_scaled, labels)):
        # print(f"\n=== Fold {fold + 1}/{n_folds} ===")
        
        train_data, val_data = frb_data_scaled[train_index], frb_data_scaled[val_index]
        train_labels, val_labels = labels.iloc[train_index], labels.iloc[val_index]
        
        train_tensor = torch.tensor(train_data, dtype=torch.float32)
        val_tensor = torch.tensor(val_data, dtype=torch.float32)
        train_labels_tensor = torch.tensor(train_labels.values, dtype=torch.long)
        val_labels_tensor = torch.tensor(val_labels.values, dtype=torch.long)
        
        train_dataset = TensorDataset(train_tensor, train_labels_tensor)
        val_dataset = TensorDataset(val_tensor, val_labels_tensor)
        
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
        

        
        optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
        scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=4)
        
        # Train the model
        for epoch in range(1, num_epochs + 1):
            train_loss, _, _, _, train_accuracy = train_supervised(model, optimizer, scheduler, epoch, beta, gamma)
            val_loss, _, _, _, val_accuracy = validate_supervised(model, optimizer, scheduler, epoch, beta, gamma)
            scheduler.step(val_loss)
            
            # Early stopping
            if early_stopping([val_loss], patience):
                print(f"Early stopping triggered at epoch {epoch}")
                break

        val_accuracy, val_class_report, val_conf_matrix, val_preds, val_labels = evaluate_classifier_full(model, val_loader, device)
        
        # print(f"Validation Accuracy: {val_accuracy:.4f}")
        # print("Classification Report:\n", val_class_report)
        # print("Confusion Matrix:\n", val_conf_matrix)
        
        misclassified_non_repeaters = (val_labels == 0) & (val_preds == 1)
        misclassified_indices = val_index[misclassified_non_repeaters]
        misclassified_sources = original_data.loc[misclassified_indices, "Source"].drop_duplicates()
        
        false_positives_fold = original_data.loc[val_index[(val_labels == 0) & (val_preds == 1)], "Source"]
        false_negatives_fold = original_data.loc[val_index[(val_labels == 1) & (val_preds == 0)], "Source"]
        true_positives_fold = original_data.loc[val_index[(val_labels == 1) & (val_preds == 1)], "Source"]
        true_negatives_fold = original_data.loc[val_index[(val_labels == 0) & (val_preds == 0)], "Source"]
        
        # fold_false_positives = []
        # for source in misclassified_sources:
        #     # fold_false_positives.append(source)
        #     if source in garcia_list or source in luo_list or source in zhu_ge_list:
        #         print(f"False positive in fold {fold + 1}: {source}")
                
        all_false_negatives.extend(false_negatives_fold)
        all_true_positives.extend(true_positives_fold)
        all_true_negatives.extend(true_negatives_fold)
        all_false_positives.extend(false_positives_fold)
        
        
    all_false_positives = pd.Series(all_false_positives)
    all_false_negatives = pd.Series(all_false_negatives)
    all_true_positives = pd.Series(all_true_positives)
    all_true_negatives = pd.Series(all_true_negatives)

    print("\n=== Summary ===")
    print(f"Total False Positives: {all_false_positives.nunique()}")
    print(f"Total False Negatives: {all_false_negatives.nunique()}")
    print(f"Total True Positives: {all_true_positives.nunique()}")
    print(f"Total True Negatives: {all_true_negatives.nunique()}")

    # Confusion matrix

    conf_mat_final = np.zeros((2, 2))
    conf_mat_final[0, 0] = all_true_negatives.nunique()
    conf_mat_final[0, 1] = all_false_positives.nunique()
    conf_mat_final[1, 0] = all_false_negatives.nunique()
    conf_mat_final[1, 1] = all_true_positives.nunique()
    conf_mat_final.astype(int)
    print(conf_mat_final)

    recall = all_true_positives.nunique() / (all_true_positives.nunique() + all_false_negatives.nunique())
    
    return recall
        
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

print("Best Hyperparameters:", study.best_params)

[I 2024-11-17 21:53:32,675] A new study created in memory with name: no-name-633fc457-2ba0-4cb1-8d60-428618272494
[I 2024-11-17 21:55:13,418] Trial 0 finished with value: 0.6666666666666666 and parameters: {'hidden_dim': 279, 'latent_dim': 18, 'beta': 1.339312908392761, 'gamma': 0.5068503233303048, 'dropout_rate': 0.14106274981524086, 'activation': 'ReLU'}. Best is trial 0 with value: 0.6666666666666666.



=== Summary ===
Total False Positives: 137
Total False Negatives: 33
Total True Positives: 66
Total True Negatives: 613
[[613. 137.]
 [ 33.  66.]]


[I 2024-11-17 21:56:54,684] Trial 1 finished with value: 0.6947368421052632 and parameters: {'hidden_dim': 371, 'latent_dim': 6, 'beta': 0.8987092220367706, 'gamma': 1.8852569856078423, 'dropout_rate': 0.4264255834156089, 'activation': 'ReLU'}. Best is trial 1 with value: 0.6947368421052632.



=== Summary ===
Total False Positives: 90
Total False Negatives: 29
Total True Positives: 66
Total True Negatives: 660
[[660.  90.]
 [ 29.  66.]]


[I 2024-11-17 21:58:36,038] Trial 2 finished with value: 0.7415730337078652 and parameters: {'hidden_dim': 380, 'latent_dim': 6, 'beta': 0.8521615908582372, 'gamma': 0.5080368171092521, 'dropout_rate': 0.29901548376355536, 'activation': 'SELU'}. Best is trial 2 with value: 0.7415730337078652.



=== Summary ===
Total False Positives: 137
Total False Negatives: 23
Total True Positives: 66
Total True Negatives: 612
[[612. 137.]
 [ 23.  66.]]


[I 2024-11-17 22:00:18,008] Trial 3 finished with value: 0.6836734693877551 and parameters: {'hidden_dim': 444, 'latent_dim': 18, 'beta': 1.8359117937102913, 'gamma': 1.5871550417469842, 'dropout_rate': 0.43801050262698604, 'activation': 'LeakyReLU'}. Best is trial 2 with value: 0.7415730337078652.



=== Summary ===
Total False Positives: 310
Total False Negatives: 31
Total True Positives: 67
Total True Negatives: 439
[[439. 310.]
 [ 31.  67.]]


[I 2024-11-17 22:02:02,244] Trial 4 finished with value: 0.7096774193548387 and parameters: {'hidden_dim': 507, 'latent_dim': 11, 'beta': 0.9929888983198583, 'gamma': 1.4164687497088293, 'dropout_rate': 0.40634767744327427, 'activation': 'ReLU'}. Best is trial 2 with value: 0.7415730337078652.



=== Summary ===
Total False Positives: 140
Total False Negatives: 27
Total True Positives: 66
Total True Negatives: 610
[[610. 140.]
 [ 27.  66.]]


[I 2024-11-17 22:03:40,338] Trial 5 finished with value: 0.6979166666666666 and parameters: {'hidden_dim': 143, 'latent_dim': 13, 'beta': 1.3859154295149785, 'gamma': 1.074894977515466, 'dropout_rate': 0.2257285750581952, 'activation': 'ELU'}. Best is trial 2 with value: 0.7415730337078652.



=== Summary ===
Total False Positives: 232
Total False Negatives: 29
Total True Positives: 67
Total True Negatives: 517
[[517. 232.]
 [ 29.  67.]]


[I 2024-11-17 22:05:17,906] Trial 6 finished with value: 0.6534653465346535 and parameters: {'hidden_dim': 230, 'latent_dim': 20, 'beta': 1.8968670114825856, 'gamma': 1.0505645779285697, 'dropout_rate': 0.1499141381402153, 'activation': 'ELU'}. Best is trial 2 with value: 0.7415730337078652.



=== Summary ===
Total False Positives: 280
Total False Negatives: 35
Total True Positives: 66
Total True Negatives: 469
[[469. 280.]
 [ 35.  66.]]


[I 2024-11-17 22:06:58,024] Trial 7 finished with value: 0.6907216494845361 and parameters: {'hidden_dim': 496, 'latent_dim': 8, 'beta': 1.5096663384727993, 'gamma': 1.6605444086419834, 'dropout_rate': 0.20040032421833578, 'activation': 'SELU'}. Best is trial 2 with value: 0.7415730337078652.



=== Summary ===
Total False Positives: 172
Total False Negatives: 30
Total True Positives: 67
Total True Negatives: 578
[[578. 172.]
 [ 30.  67.]]


[I 2024-11-17 22:08:37,387] Trial 8 finished with value: 0.6907216494845361 and parameters: {'hidden_dim': 137, 'latent_dim': 15, 'beta': 0.5509667971563789, 'gamma': 0.5303727388756363, 'dropout_rate': 0.46353991573720643, 'activation': 'ELU'}. Best is trial 2 with value: 0.7415730337078652.



=== Summary ===
Total False Positives: 185
Total False Negatives: 30
Total True Positives: 67
Total True Negatives: 564
[[564. 185.]
 [ 30.  67.]]


[I 2024-11-17 22:10:15,704] Trial 9 finished with value: 0.6203703703703703 and parameters: {'hidden_dim': 190, 'latent_dim': 11, 'beta': 1.7290840096521252, 'gamma': 1.8534231822979954, 'dropout_rate': 0.4828462199598378, 'activation': 'ELU'}. Best is trial 2 with value: 0.7415730337078652.



=== Summary ===
Total False Positives: 332
Total False Negatives: 41
Total True Positives: 67
Total True Negatives: 417
[[417. 332.]
 [ 41.  67.]]


[I 2024-11-17 22:11:58,243] Trial 10 finished with value: 0.7764705882352941 and parameters: {'hidden_dim': 362, 'latent_dim': 5, 'beta': 0.5080510979863286, 'gamma': 0.8282475783938439, 'dropout_rate': 0.3280036533385225, 'activation': 'SELU'}. Best is trial 10 with value: 0.7764705882352941.



=== Summary ===
Total False Positives: 105
Total False Negatives: 19
Total True Positives: 66
Total True Negatives: 644
[[644. 105.]
 [ 19.  66.]]


[I 2024-11-17 22:13:41,416] Trial 11 finished with value: 0.788235294117647 and parameters: {'hidden_dim': 355, 'latent_dim': 5, 'beta': 0.5002365604727008, 'gamma': 0.7855322272029938, 'dropout_rate': 0.3325257302524663, 'activation': 'SELU'}. Best is trial 11 with value: 0.788235294117647.



=== Summary ===
Total False Positives: 108
Total False Negatives: 18
Total True Positives: 67
Total True Negatives: 642
[[642. 108.]
 [ 18.  67.]]


[I 2024-11-17 22:15:21,265] Trial 12 finished with value: 0.7282608695652174 and parameters: {'hidden_dim': 335, 'latent_dim': 5, 'beta': 0.5055174308735566, 'gamma': 0.8465304241835667, 'dropout_rate': 0.3311316911985932, 'activation': 'GELU'}. Best is trial 11 with value: 0.788235294117647.



=== Summary ===
Total False Positives: 53
Total False Negatives: 25
Total True Positives: 67
Total True Negatives: 697
[[697.  53.]
 [ 25.  67.]]


[I 2024-11-17 22:17:04,637] Trial 13 finished with value: 0.7204301075268817 and parameters: {'hidden_dim': 412, 'latent_dim': 9, 'beta': 0.713471178524139, 'gamma': 0.8304604226503524, 'dropout_rate': 0.3369374015745339, 'activation': 'SELU'}. Best is trial 11 with value: 0.788235294117647.



=== Summary ===
Total False Positives: 111
Total False Negatives: 26
Total True Positives: 67
Total True Negatives: 638
[[638. 111.]
 [ 26.  67.]]


[I 2024-11-17 22:18:46,551] Trial 14 finished with value: 0.7096774193548387 and parameters: {'hidden_dim': 281, 'latent_dim': 8, 'beta': 1.094609230136452, 'gamma': 0.7890866562293548, 'dropout_rate': 0.28457398772475323, 'activation': 'SELU'}. Best is trial 11 with value: 0.788235294117647.



=== Summary ===
Total False Positives: 195
Total False Negatives: 27
Total True Positives: 66
Total True Negatives: 554
[[554. 195.]
 [ 27.  66.]]


[I 2024-11-17 22:20:29,298] Trial 15 finished with value: 0.7674418604651163 and parameters: {'hidden_dim': 308, 'latent_dim': 5, 'beta': 0.7070900829272619, 'gamma': 1.168269598201083, 'dropout_rate': 0.38652014964975046, 'activation': 'SELU'}. Best is trial 11 with value: 0.788235294117647.



=== Summary ===
Total False Positives: 166
Total False Negatives: 20
Total True Positives: 66
Total True Negatives: 584
[[584. 166.]
 [ 20.  66.]]


[I 2024-11-17 22:22:12,714] Trial 16 finished with value: 0.7021276595744681 and parameters: {'hidden_dim': 446, 'latent_dim': 9, 'beta': 1.1755664778415646, 'gamma': 0.7521562831868974, 'dropout_rate': 0.26100875344618435, 'activation': 'LeakyReLU'}. Best is trial 11 with value: 0.788235294117647.



=== Summary ===
Total False Positives: 133
Total False Negatives: 28
Total True Positives: 66
Total True Negatives: 617
[[617. 133.]
 [ 28.  66.]]


[I 2024-11-17 22:23:54,452] Trial 17 finished with value: 0.7586206896551724 and parameters: {'hidden_dim': 345, 'latent_dim': 7, 'beta': 0.7037466125125436, 'gamma': 1.3295168035889364, 'dropout_rate': 0.36036512137678106, 'activation': 'GELU'}. Best is trial 11 with value: 0.788235294117647.



=== Summary ===
Total False Positives: 98
Total False Negatives: 21
Total True Positives: 66
Total True Negatives: 652
[[652.  98.]
 [ 21.  66.]]


[I 2024-11-17 22:25:37,330] Trial 18 finished with value: 0.8170731707317073 and parameters: {'hidden_dim': 392, 'latent_dim': 14, 'beta': 0.5100334702934927, 'gamma': 0.9550260315645138, 'dropout_rate': 0.23948356766090378, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 56
Total False Negatives: 15
Total True Positives: 67
Total True Negatives: 693
[[693.  56.]
 [ 15.  67.]]


[I 2024-11-17 22:27:19,085] Trial 19 finished with value: 0.7790697674418605 and parameters: {'hidden_dim': 411, 'latent_dim': 14, 'beta': 0.8313304934367095, 'gamma': 1.0068788505193698, 'dropout_rate': 0.21374526699821417, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 114
Total False Negatives: 19
Total True Positives: 67
Total True Negatives: 636
[[636. 114.]
 [ 19.  67.]]


[I 2024-11-17 22:28:58,152] Trial 20 finished with value: 0.6767676767676768 and parameters: {'hidden_dim': 233, 'latent_dim': 16, 'beta': 0.6442298843805825, 'gamma': 0.6594574459841982, 'dropout_rate': 0.26533036305821184, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 102
Total False Negatives: 32
Total True Positives: 67
Total True Negatives: 648
[[648. 102.]
 [ 32.  67.]]


[I 2024-11-17 22:30:41,086] Trial 21 finished with value: 0.7096774193548387 and parameters: {'hidden_dim': 412, 'latent_dim': 14, 'beta': 0.8662883686028818, 'gamma': 0.9967449183282826, 'dropout_rate': 0.20007440412424132, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 124
Total False Negatives: 27
Total True Positives: 66
Total True Negatives: 625
[[625. 124.]
 [ 27.  66.]]


[I 2024-11-17 22:32:23,869] Trial 22 finished with value: 0.7528089887640449 and parameters: {'hidden_dim': 407, 'latent_dim': 12, 'beta': 0.7942992516179151, 'gamma': 0.9636711654927929, 'dropout_rate': 0.23026072733401748, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 109
Total False Negatives: 22
Total True Positives: 67
Total True Negatives: 640
[[640. 109.]
 [ 22.  67.]]


[I 2024-11-17 22:34:04,440] Trial 23 finished with value: 0.7204301075268817 and parameters: {'hidden_dim': 319, 'latent_dim': 16, 'beta': 1.0176665320938143, 'gamma': 1.2221479920871698, 'dropout_rate': 0.1009335393114662, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 148
Total False Negatives: 26
Total True Positives: 67
Total True Negatives: 602
[[602. 148.]
 [ 26.  67.]]


[I 2024-11-17 22:35:51,051] Trial 24 finished with value: 0.7790697674418605 and parameters: {'hidden_dim': 458, 'latent_dim': 13, 'beta': 0.6152024452800844, 'gamma': 0.96682123150243, 'dropout_rate': 0.180588841653915, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 48
Total False Negatives: 19
Total True Positives: 67
Total True Negatives: 701
[[701.  48.]
 [ 19.  67.]]


[I 2024-11-17 22:37:36,743] Trial 25 finished with value: 0.7362637362637363 and parameters: {'hidden_dim': 386, 'latent_dim': 11, 'beta': 0.7713582081469504, 'gamma': 0.6452449366743541, 'dropout_rate': 0.25062245626453244, 'activation': 'LeakyReLU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 92
Total False Negatives: 24
Total True Positives: 67
Total True Negatives: 658
[[658.  92.]
 [ 24.  67.]]


[I 2024-11-17 22:39:20,517] Trial 26 finished with value: 0.7052631578947368 and parameters: {'hidden_dim': 474, 'latent_dim': 15, 'beta': 0.6081986334162001, 'gamma': 1.1289700848199606, 'dropout_rate': 0.2980794436990706, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 53
Total False Negatives: 28
Total True Positives: 67
Total True Negatives: 696
[[696.  53.]
 [ 28.  67.]]


[I 2024-11-17 22:41:00,345] Trial 27 finished with value: 0.7052631578947368 and parameters: {'hidden_dim': 421, 'latent_dim': 17, 'beta': 0.9722753999922973, 'gamma': 1.3223549836504076, 'dropout_rate': 0.2288608881078114, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 187
Total False Negatives: 28
Total True Positives: 67
Total True Negatives: 563
[[563. 187.]
 [ 28.  67.]]


[I 2024-11-17 22:42:42,403] Trial 28 finished with value: 0.7282608695652174 and parameters: {'hidden_dim': 294, 'latent_dim': 14, 'beta': 1.16237802744882, 'gamma': 0.9185837341751729, 'dropout_rate': 0.1592833632445233, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 178
Total False Negatives: 25
Total True Positives: 67
Total True Negatives: 571
[[571. 178.]
 [ 25.  67.]]


[I 2024-11-17 22:44:24,170] Trial 29 finished with value: 0.7701149425287356 and parameters: {'hidden_dim': 256, 'latent_dim': 19, 'beta': 0.5012887389331445, 'gamma': 0.7165189651652402, 'dropout_rate': 0.36708755161936896, 'activation': 'ReLU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 66
Total False Negatives: 20
Total True Positives: 67
Total True Negatives: 684
[[684.  66.]
 [ 20.  67.]]


[I 2024-11-17 22:46:05,647] Trial 30 finished with value: 0.6979166666666666 and parameters: {'hidden_dim': 347, 'latent_dim': 10, 'beta': 1.2750276787860664, 'gamma': 0.897469656494342, 'dropout_rate': 0.11487711288009174, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 165
Total False Negatives: 29
Total True Positives: 67
Total True Negatives: 585
[[585. 165.]
 [ 29.  67.]]


[I 2024-11-17 22:47:49,157] Trial 31 finished with value: 0.7701149425287356 and parameters: {'hidden_dim': 461, 'latent_dim': 13, 'beta': 0.6189774400663675, 'gamma': 0.9975286441831377, 'dropout_rate': 0.17567048019764725, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 68
Total False Negatives: 20
Total True Positives: 67
Total True Negatives: 681
[[681.  68.]
 [ 20.  67.]]


[I 2024-11-17 22:49:31,954] Trial 32 finished with value: 0.7528089887640449 and parameters: {'hidden_dim': 438, 'latent_dim': 12, 'beta': 0.651099326606625, 'gamma': 1.1265357181674875, 'dropout_rate': 0.2013413640440236, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 93
Total False Negatives: 22
Total True Positives: 67
Total True Negatives: 657
[[657.  93.]
 [ 22.  67.]]


[I 2024-11-17 22:51:14,284] Trial 33 finished with value: 0.7764705882352941 and parameters: {'hidden_dim': 389, 'latent_dim': 14, 'beta': 0.8005287328428803, 'gamma': 0.6002710215323841, 'dropout_rate': 0.17510259446734108, 'activation': 'ReLU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 65
Total False Negatives: 19
Total True Positives: 66
Total True Negatives: 684
[[684.  65.]
 [ 19.  66.]]


[I 2024-11-17 22:52:58,039] Trial 34 finished with value: 0.6979166666666666 and parameters: {'hidden_dim': 472, 'latent_dim': 15, 'beta': 0.9252489009217122, 'gamma': 0.9289964351541107, 'dropout_rate': 0.2789408970757791, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 164
Total False Negatives: 29
Total True Positives: 67
Total True Negatives: 586
[[586. 164.]
 [ 29.  67.]]


[I 2024-11-17 22:54:42,112] Trial 35 finished with value: 0.7362637362637363 and parameters: {'hidden_dim': 359, 'latent_dim': 17, 'beta': 0.5987396368191805, 'gamma': 1.2420808782060857, 'dropout_rate': 0.12902007000647808, 'activation': 'LeakyReLU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 33
Total False Negatives: 24
Total True Positives: 67
Total True Negatives: 716
[[716.  33.]
 [ 24.  67.]]


[I 2024-11-17 22:56:26,951] Trial 36 finished with value: 0.7282608695652174 and parameters: {'hidden_dim': 378, 'latent_dim': 13, 'beta': 0.7354823684462206, 'gamma': 1.0552749409878128, 'dropout_rate': 0.24169833164094456, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 99
Total False Negatives: 25
Total True Positives: 67
Total True Negatives: 650
[[650.  99.]
 [ 25.  67.]]


[I 2024-11-17 22:58:11,451] Trial 37 finished with value: 0.7065217391304348 and parameters: {'hidden_dim': 491, 'latent_dim': 12, 'beta': 0.8471871683709479, 'gamma': 1.4347516488273855, 'dropout_rate': 0.30966772634236306, 'activation': 'ReLU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 93
Total False Negatives: 27
Total True Positives: 65
Total True Negatives: 657
[[657.  93.]
 [ 27.  65.]]


[I 2024-11-17 22:59:56,008] Trial 38 finished with value: 0.6736842105263158 and parameters: {'hidden_dim': 432, 'latent_dim': 10, 'beta': 1.5144383096479277, 'gamma': 0.7285510154645497, 'dropout_rate': 0.213082771367185, 'activation': 'SELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 204
Total False Negatives: 31
Total True Positives: 64
Total True Negatives: 546
[[546. 204.]
 [ 31.  64.]]


[I 2024-11-17 23:01:37,930] Trial 39 finished with value: 0.7976190476190477 and parameters: {'hidden_dim': 398, 'latent_dim': 14, 'beta': 0.5762344877547114, 'gamma': 1.0428795084783298, 'dropout_rate': 0.16786300402326565, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 39
Total False Negatives: 17
Total True Positives: 67
Total True Negatives: 710
[[710.  39.]
 [ 17.  67.]]


[I 2024-11-17 23:03:22,168] Trial 40 finished with value: 0.788235294117647 and parameters: {'hidden_dim': 403, 'latent_dim': 17, 'beta': 0.5865637264390953, 'gamma': 1.0421767313217625, 'dropout_rate': 0.14204243916800685, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 41
Total False Negatives: 18
Total True Positives: 67
Total True Negatives: 708
[[708.  41.]
 [ 18.  67.]]


[I 2024-11-17 23:05:03,723] Trial 41 finished with value: 0.8170731707317073 and parameters: {'hidden_dim': 392, 'latent_dim': 17, 'beta': 0.5885762428050315, 'gamma': 1.0713434816692686, 'dropout_rate': 0.1341166118248488, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 34
Total False Negatives: 15
Total True Positives: 67
Total True Negatives: 716
[[716.  34.]
 [ 15.  67.]]


[I 2024-11-17 23:06:47,624] Trial 42 finished with value: 0.8072289156626506 and parameters: {'hidden_dim': 394, 'latent_dim': 18, 'beta': 0.5544500608501866, 'gamma': 1.107469460493449, 'dropout_rate': 0.1573053477724778, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 37
Total False Negatives: 16
Total True Positives: 67
Total True Negatives: 712
[[712.  37.]
 [ 16.  67.]]


[I 2024-11-17 23:08:32,477] Trial 43 finished with value: 0.788235294117647 and parameters: {'hidden_dim': 368, 'latent_dim': 20, 'beta': 0.5520737288520327, 'gamma': 1.157466092050907, 'dropout_rate': 0.1313530485207318, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 18
Total False Negatives: 18
Total True Positives: 67
Total True Negatives: 731
[[731.  18.]
 [ 18.  67.]]


[I 2024-11-17 23:10:13,582] Trial 44 finished with value: 0.7444444444444445 and parameters: {'hidden_dim': 333, 'latent_dim': 19, 'beta': 0.6850201837779741, 'gamma': 1.333471572124085, 'dropout_rate': 0.15447774872018524, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 60
Total False Negatives: 23
Total True Positives: 67
Total True Negatives: 690
[[690.  60.]
 [ 23.  67.]]


[I 2024-11-17 23:11:53,952] Trial 45 finished with value: 0.7976190476190477 and parameters: {'hidden_dim': 392, 'latent_dim': 18, 'beta': 0.5061104204180464, 'gamma': 0.8700481814448738, 'dropout_rate': 0.1015830116231393, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 28
Total False Negatives: 17
Total True Positives: 67
Total True Negatives: 721
[[721.  28.]
 [ 17.  67.]]


[I 2024-11-17 23:13:34,942] Trial 46 finished with value: 0.8072289156626506 and parameters: {'hidden_dim': 395, 'latent_dim': 18, 'beta': 0.559614721615577, 'gamma': 0.8700265821701403, 'dropout_rate': 0.11726941366525175, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 44
Total False Negatives: 16
Total True Positives: 67
Total True Negatives: 705
[[705.  44.]
 [ 16.  67.]]


[I 2024-11-17 23:15:16,193] Trial 47 finished with value: 0.7052631578947368 and parameters: {'hidden_dim': 427, 'latent_dim': 18, 'beta': 1.5902792646547828, 'gamma': 1.5118626599017924, 'dropout_rate': 0.1226448318065426, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 146
Total False Negatives: 28
Total True Positives: 67
Total True Negatives: 604
[[604. 146.]
 [ 28.  67.]]


[I 2024-11-17 23:16:58,399] Trial 48 finished with value: 0.7790697674418605 and parameters: {'hidden_dim': 375, 'latent_dim': 19, 'beta': 0.561302444320005, 'gamma': 1.1017657072040625, 'dropout_rate': 0.16310924158537568, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 44
Total False Negatives: 19
Total True Positives: 67
Total True Negatives: 705
[[705.  44.]
 [ 19.  67.]]


[I 2024-11-17 23:18:40,531] Trial 49 finished with value: 0.717391304347826 and parameters: {'hidden_dim': 323, 'latent_dim': 16, 'beta': 0.6809631254924225, 'gamma': 1.2043565780576997, 'dropout_rate': 0.13784301294405887, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 60
Total False Negatives: 26
Total True Positives: 66
Total True Negatives: 690
[[690.  60.]
 [ 26.  66.]]


[I 2024-11-17 23:20:23,062] Trial 50 finished with value: 0.6875 and parameters: {'hidden_dim': 397, 'latent_dim': 18, 'beta': 0.9046343117213218, 'gamma': 1.2915948224225922, 'dropout_rate': 0.18035544193971703, 'activation': 'GELU'}. Best is trial 18 with value: 0.8170731707317073.



=== Summary ===
Total False Positives: 80
Total False Negatives: 30
Total True Positives: 66
Total True Negatives: 670
[[670.  80.]
 [ 30.  66.]]


[I 2024-11-17 23:22:02,473] Trial 51 finished with value: 0.8481012658227848 and parameters: {'hidden_dim': 391, 'latent_dim': 18, 'beta': 0.5511658977785503, 'gamma': 0.8762974968656851, 'dropout_rate': 0.1031427940632989, 'activation': 'GELU'}. Best is trial 51 with value: 0.8481012658227848.



=== Summary ===
Total False Positives: 31
Total False Negatives: 12
Total True Positives: 67
Total True Negatives: 719
[[719.  31.]
 [ 12.  67.]]


[I 2024-11-17 23:23:47,903] Trial 52 finished with value: 0.8072289156626506 and parameters: {'hidden_dim': 374, 'latent_dim': 17, 'beta': 0.7304332329368426, 'gamma': 0.8206230180626318, 'dropout_rate': 0.11188784590656235, 'activation': 'GELU'}. Best is trial 51 with value: 0.8481012658227848.



=== Summary ===
Total False Positives: 68
Total False Negatives: 16
Total True Positives: 67
Total True Negatives: 681
[[681.  68.]
 [ 16.  67.]]


[I 2024-11-17 23:25:32,539] Trial 53 finished with value: 0.7701149425287356 and parameters: {'hidden_dim': 372, 'latent_dim': 17, 'beta': 0.7582237393437206, 'gamma': 0.8114181830458703, 'dropout_rate': 0.1133636823373449, 'activation': 'ELU'}. Best is trial 51 with value: 0.8481012658227848.



=== Summary ===
Total False Positives: 104
Total False Negatives: 20
Total True Positives: 67
Total True Negatives: 646
[[646. 104.]
 [ 20.  67.]]


[I 2024-11-17 23:27:16,674] Trial 54 finished with value: 0.7674418604651163 and parameters: {'hidden_dim': 352, 'latent_dim': 19, 'beta': 0.6818819702314036, 'gamma': 0.8878966073200164, 'dropout_rate': 0.14272460569682535, 'activation': 'GELU'}. Best is trial 51 with value: 0.8481012658227848.



=== Summary ===
Total False Positives: 47
Total False Negatives: 20
Total True Positives: 66
Total True Negatives: 702
[[702.  47.]
 [ 20.  66.]]


[I 2024-11-17 23:28:57,279] Trial 55 finished with value: 0.881578947368421 and parameters: {'hidden_dim': 420, 'latent_dim': 20, 'beta': 0.5507149759264907, 'gamma': 1.7790440339348805, 'dropout_rate': 0.11384375970675616, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 30
Total False Negatives: 9
Total True Positives: 67
Total True Negatives: 719
[[719.  30.]
 [  9.  67.]]


[I 2024-11-17 23:30:41,103] Trial 56 finished with value: 0.788235294117647 and parameters: {'hidden_dim': 450, 'latent_dim': 20, 'beta': 0.5638348766981331, 'gamma': 1.9490651455829489, 'dropout_rate': 0.14918647769891805, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 37
Total False Negatives: 18
Total True Positives: 67
Total True Negatives: 713
[[713.  37.]
 [ 18.  67.]]


[I 2024-11-17 23:32:21,138] Trial 57 finished with value: 0.8375 and parameters: {'hidden_dim': 418, 'latent_dim': 18, 'beta': 0.6429583227148818, 'gamma': 1.7726409710202127, 'dropout_rate': 0.1932356153574434, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 34
Total False Negatives: 13
Total True Positives: 67
Total True Negatives: 715
[[715.  34.]
 [ 13.  67.]]


[I 2024-11-17 23:34:04,964] Trial 58 finished with value: 0.7857142857142857 and parameters: {'hidden_dim': 421, 'latent_dim': 20, 'beta': 0.6336787712175549, 'gamma': 1.8113988340409661, 'dropout_rate': 0.19275776389268, 'activation': 'ELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 71
Total False Negatives: 18
Total True Positives: 66
Total True Negatives: 678
[[678.  71.]
 [ 18.  66.]]


[I 2024-11-17 23:35:50,988] Trial 59 finished with value: 0.7613636363636364 and parameters: {'hidden_dim': 439, 'latent_dim': 19, 'beta': 0.6531448977426002, 'gamma': 1.718730823288581, 'dropout_rate': 0.12746091497975376, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 37
Total False Negatives: 21
Total True Positives: 67
Total True Negatives: 713
[[713.  37.]
 [ 21.  67.]]


[I 2024-11-17 23:37:36,059] Trial 60 finished with value: 0.8481012658227848 and parameters: {'hidden_dim': 508, 'latent_dim': 16, 'beta': 0.5390343079394431, 'gamma': 1.6818389254057702, 'dropout_rate': 0.21562177522659853, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 26
Total False Negatives: 12
Total True Positives: 67
Total True Negatives: 724
[[724.  26.]
 [ 12.  67.]]


[I 2024-11-17 23:39:18,929] Trial 61 finished with value: 0.8701298701298701 and parameters: {'hidden_dim': 500, 'latent_dim': 16, 'beta': 0.5099036281785101, 'gamma': 1.7600985385958459, 'dropout_rate': 0.19143423443740384, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 35
Total False Negatives: 10
Total True Positives: 67
Total True Negatives: 715
[[715.  35.]
 [ 10.  67.]]


[I 2024-11-17 23:40:58,133] Trial 62 finished with value: 0.8701298701298701 and parameters: {'hidden_dim': 500, 'latent_dim': 16, 'beta': 0.5271585775847245, 'gamma': 1.7088413183166629, 'dropout_rate': 0.21467840288733503, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 37
Total False Negatives: 10
Total True Positives: 67
Total True Negatives: 713
[[713.  37.]
 [ 10.  67.]]


[I 2024-11-17 23:42:41,966] Trial 63 finished with value: 0.7790697674418605 and parameters: {'hidden_dim': 501, 'latent_dim': 16, 'beta': 0.5200490267396397, 'gamma': 1.6818987854787175, 'dropout_rate': 0.21345532896561153, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 30
Total False Negatives: 19
Total True Positives: 67
Total True Negatives: 719
[[719.  30.]
 [ 19.  67.]]


[I 2024-11-17 23:44:25,338] Trial 64 finished with value: 0.8170731707317073 and parameters: {'hidden_dim': 493, 'latent_dim': 15, 'beta': 0.5277810060994815, 'gamma': 1.772126727943758, 'dropout_rate': 0.19023095000868973, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 41
Total False Negatives: 15
Total True Positives: 67
Total True Negatives: 708
[[708.  41.]
 [ 15.  67.]]


[I 2024-11-17 23:46:13,459] Trial 65 finished with value: 0.6979166666666666 and parameters: {'hidden_dim': 510, 'latent_dim': 15, 'beta': 1.3765609542592288, 'gamma': 1.896082289096864, 'dropout_rate': 0.25319542856395055, 'activation': 'LeakyReLU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 134
Total False Negatives: 29
Total True Positives: 67
Total True Negatives: 616
[[616. 134.]
 [ 29.  67.]]


[I 2024-11-17 23:47:57,663] Trial 66 finished with value: 0.8271604938271605 and parameters: {'hidden_dim': 482, 'latent_dim': 16, 'beta': 0.6618235152117128, 'gamma': 1.554336548075035, 'dropout_rate': 0.2409581214620112, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 65
Total False Negatives: 14
Total True Positives: 67
Total True Negatives: 684
[[684.  65.]
 [ 14.  67.]]


[I 2024-11-17 23:49:41,536] Trial 67 finished with value: 0.673469387755102 and parameters: {'hidden_dim': 478, 'latent_dim': 16, 'beta': 1.9285720721202362, 'gamma': 1.602751854002623, 'dropout_rate': 0.2702494206707199, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 199
Total False Negatives: 32
Total True Positives: 66
Total True Negatives: 550
[[550. 199.]
 [ 32.  66.]]


[I 2024-11-17 23:51:26,914] Trial 68 finished with value: 0.7021276595744681 and parameters: {'hidden_dim': 479, 'latent_dim': 16, 'beta': 1.8140094200156205, 'gamma': 1.6118462552243993, 'dropout_rate': 0.21880573800368075, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 163
Total False Negatives: 28
Total True Positives: 66
Total True Negatives: 586
[[586. 163.]
 [ 28.  66.]]


[I 2024-11-17 23:53:13,421] Trial 69 finished with value: 0.7127659574468085 and parameters: {'hidden_dim': 461, 'latent_dim': 19, 'beta': 0.8083720043956162, 'gamma': 1.51003667567501, 'dropout_rate': 0.4349815167881116, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 95
Total False Negatives: 27
Total True Positives: 67
Total True Negatives: 654
[[654.  95.]
 [ 27.  67.]]


[I 2024-11-17 23:54:55,735] Trial 70 finished with value: 0.7528089887640449 and parameters: {'hidden_dim': 512, 'latent_dim': 16, 'beta': 0.656846787954912, 'gamma': 1.75097960927899, 'dropout_rate': 0.23801221777770226, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 39
Total False Negatives: 22
Total True Positives: 67
Total True Negatives: 710
[[710.  39.]
 [ 22.  67.]]


[I 2024-11-17 23:56:38,553] Trial 71 finished with value: 0.8375 and parameters: {'hidden_dim': 485, 'latent_dim': 15, 'beta': 0.6099041258827824, 'gamma': 1.8413795561069803, 'dropout_rate': 0.20450250842320072, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 39
Total False Negatives: 13
Total True Positives: 67
Total True Negatives: 710
[[710.  39.]
 [ 13.  67.]]


[I 2024-11-17 23:58:14,541] Trial 72 finished with value: 0.7790697674418605 and parameters: {'hidden_dim': 487, 'latent_dim': 15, 'beta': 0.6047387964989375, 'gamma': 1.8391130155835995, 'dropout_rate': 0.20234723103551389, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 35
Total False Negatives: 19
Total True Positives: 67
Total True Negatives: 715
[[715.  35.]
 [ 19.  67.]]


[I 2024-11-17 23:59:54,821] Trial 73 finished with value: 0.75 and parameters: {'hidden_dim': 501, 'latent_dim': 17, 'beta': 0.7132942778340672, 'gamma': 1.9949986497884296, 'dropout_rate': 0.22425615025689252, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 67
Total False Negatives: 22
Total True Positives: 66
Total True Negatives: 682
[[682.  67.]
 [ 22.  66.]]


[I 2024-11-18 00:01:34,445] Trial 74 finished with value: 0.8375 and parameters: {'hidden_dim': 469, 'latent_dim': 18, 'beta': 0.7603997575749087, 'gamma': 1.6570422004277419, 'dropout_rate': 0.184393499914961, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 57
Total False Negatives: 13
Total True Positives: 67
Total True Negatives: 693
[[693.  57.]
 [ 13.  67.]]


[I 2024-11-18 00:03:15,821] Trial 75 finished with value: 0.7701149425287356 and parameters: {'hidden_dim': 466, 'latent_dim': 18, 'beta': 0.7580403201488852, 'gamma': 1.6668473407478928, 'dropout_rate': 0.19678897363718423, 'activation': 'ReLU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 56
Total False Negatives: 20
Total True Positives: 67
Total True Negatives: 693
[[693.  56.]
 [ 20.  67.]]


[I 2024-11-18 00:04:53,379] Trial 76 finished with value: 0.7613636363636364 and parameters: {'hidden_dim': 452, 'latent_dim': 20, 'beta': 0.6208367960066772, 'gamma': 1.904372064057997, 'dropout_rate': 0.18120215528665437, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 49
Total False Negatives: 21
Total True Positives: 67
Total True Negatives: 700
[[700.  49.]
 [ 21.  67.]]


[I 2024-11-18 00:06:28,984] Trial 77 finished with value: 0.8048780487804879 and parameters: {'hidden_dim': 153, 'latent_dim': 18, 'beta': 0.5020512994572597, 'gamma': 1.7794155996513508, 'dropout_rate': 0.2089692026376291, 'activation': 'ELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 104
Total False Negatives: 16
Total True Positives: 66
Total True Negatives: 646
[[646. 104.]
 [ 16.  66.]]


[I 2024-11-18 00:08:07,037] Trial 78 finished with value: 0.7333333333333333 and parameters: {'hidden_dim': 492, 'latent_dim': 17, 'beta': 1.0440627229642674, 'gamma': 1.7173408497224774, 'dropout_rate': 0.16595040033915542, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 104
Total False Negatives: 24
Total True Positives: 66
Total True Negatives: 646
[[646. 104.]
 [ 24.  66.]]


[I 2024-11-18 00:09:44,499] Trial 79 finished with value: 0.7701149425287356 and parameters: {'hidden_dim': 469, 'latent_dim': 19, 'beta': 0.5415308772198264, 'gamma': 1.8556717290648905, 'dropout_rate': 0.18715618860988287, 'activation': 'LeakyReLU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 33
Total False Negatives: 20
Total True Positives: 67
Total True Negatives: 716
[[716.  33.]
 [ 20.  67.]]


[I 2024-11-18 00:11:24,051] Trial 80 finished with value: 0.8375 and parameters: {'hidden_dim': 504, 'latent_dim': 15, 'beta': 0.6248447970648341, 'gamma': 1.6236014193974049, 'dropout_rate': 0.17247890631793775, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 59
Total False Negatives: 13
Total True Positives: 67
Total True Negatives: 691
[[691.  59.]
 [ 13.  67.]]


[I 2024-11-18 00:13:03,234] Trial 81 finished with value: 0.8375 and parameters: {'hidden_dim': 501, 'latent_dim': 14, 'beta': 0.6139390206418694, 'gamma': 1.7058178451484918, 'dropout_rate': 0.1683216136702354, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 48
Total False Negatives: 13
Total True Positives: 67
Total True Negatives: 702
[[702.  48.]
 [ 13.  67.]]


[I 2024-11-18 00:14:42,033] Trial 82 finished with value: 0.8375 and parameters: {'hidden_dim': 487, 'latent_dim': 15, 'beta': 0.5841710490612224, 'gamma': 1.6379035114723761, 'dropout_rate': 0.14873349648390605, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 34
Total False Negatives: 13
Total True Positives: 67
Total True Negatives: 715
[[715.  34.]
 [ 13.  67.]]


[I 2024-11-18 00:16:19,858] Trial 83 finished with value: 0.788235294117647 and parameters: {'hidden_dim': 508, 'latent_dim': 15, 'beta': 0.7079178204470566, 'gamma': 1.8064257175553105, 'dropout_rate': 0.22841242633148373, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 52
Total False Negatives: 18
Total True Positives: 67
Total True Negatives: 698
[[698.  52.]
 [ 18.  67.]]


[I 2024-11-18 00:17:56,077] Trial 84 finished with value: 0.8072289156626506 and parameters: {'hidden_dim': 453, 'latent_dim': 17, 'beta': 0.6363035627613642, 'gamma': 1.560589124192556, 'dropout_rate': 0.2074976220478319, 'activation': 'GELU'}. Best is trial 55 with value: 0.881578947368421.



=== Summary ===
Total False Positives: 54
Total False Negatives: 16
Total True Positives: 67
Total True Negatives: 695
[[695.  54.]
 [ 16.  67.]]


[I 2024-11-18 00:19:34,090] Trial 85 finished with value: 0.9178082191780822 and parameters: {'hidden_dim': 476, 'latent_dim': 16, 'beta': 0.5494693076818475, 'gamma': 1.7424041881705277, 'dropout_rate': 0.10253196823027107, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 31
Total False Negatives: 6
Total True Positives: 67
Total True Negatives: 718
[[718.  31.]
 [  6.  67.]]


[I 2024-11-18 00:21:13,041] Trial 86 finished with value: 0.8072289156626506 and parameters: {'hidden_dim': 441, 'latent_dim': 16, 'beta': 0.5342799477953152, 'gamma': 1.9328232497011837, 'dropout_rate': 0.10015759857814506, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 45
Total False Negatives: 16
Total True Positives: 67
Total True Negatives: 704
[[704.  45.]
 [ 16.  67.]]


[I 2024-11-18 00:22:51,911] Trial 87 finished with value: 0.788235294117647 and parameters: {'hidden_dim': 471, 'latent_dim': 18, 'beta': 0.5808931644356645, 'gamma': 1.7415414115125099, 'dropout_rate': 0.11022316832214721, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 32
Total False Negatives: 18
Total True Positives: 67
Total True Negatives: 717
[[717.  32.]
 [ 18.  67.]]


[I 2024-11-18 00:24:31,166] Trial 88 finished with value: 0.7528089887640449 and parameters: {'hidden_dim': 419, 'latent_dim': 17, 'beta': 0.5402457555745956, 'gamma': 1.8513097553784756, 'dropout_rate': 0.3117807590025178, 'activation': 'ReLU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 44
Total False Negatives: 22
Total True Positives: 67
Total True Negatives: 705
[[705.  44.]
 [ 22.  67.]]


[I 2024-11-18 00:26:08,608] Trial 89 finished with value: 0.6504854368932039 and parameters: {'hidden_dim': 482, 'latent_dim': 16, 'beta': 1.9969797482634863, 'gamma': 1.7949918578799875, 'dropout_rate': 0.12159317071778722, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 208
Total False Negatives: 36
Total True Positives: 67
Total True Negatives: 541
[[541. 208.]
 [ 36.  67.]]


[I 2024-11-18 00:27:44,645] Trial 90 finished with value: 0.8375 and parameters: {'hidden_dim': 433, 'latent_dim': 18, 'beta': 0.6743860045324671, 'gamma': 1.675026294846801, 'dropout_rate': 0.1871826926403362, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 48
Total False Negatives: 13
Total True Positives: 67
Total True Negatives: 701
[[701.  48.]
 [ 13.  67.]]


[I 2024-11-18 00:29:22,272] Trial 91 finished with value: 0.8271604938271605 and parameters: {'hidden_dim': 499, 'latent_dim': 14, 'beta': 0.5864835944323425, 'gamma': 1.6208067952199874, 'dropout_rate': 0.17016060561707697, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 35
Total False Negatives: 14
Total True Positives: 67
Total True Negatives: 714
[[714.  35.]
 [ 14.  67.]]


[I 2024-11-18 00:31:02,764] Trial 92 finished with value: 0.7790697674418605 and parameters: {'hidden_dim': 461, 'latent_dim': 15, 'beta': 0.6214714294436088, 'gamma': 1.7496519838156648, 'dropout_rate': 0.22260221477074624, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 43
Total False Negatives: 19
Total True Positives: 67
Total True Negatives: 706
[[706.  43.]
 [ 19.  67.]]


[I 2024-11-18 00:32:38,517] Trial 93 finished with value: 0.8375 and parameters: {'hidden_dim': 512, 'latent_dim': 15, 'beta': 0.5017604307810619, 'gamma': 1.4324501955400377, 'dropout_rate': 0.20095499957919627, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 34
Total False Negatives: 13
Total True Positives: 67
Total True Negatives: 716
[[716.  34.]
 [ 13.  67.]]


[I 2024-11-18 00:34:17,158] Trial 94 finished with value: 0.6804123711340206 and parameters: {'hidden_dim': 496, 'latent_dim': 16, 'beta': 0.7487359699750871, 'gamma': 1.641742075702664, 'dropout_rate': 0.4809657168351492, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 109
Total False Negatives: 31
Total True Positives: 66
Total True Negatives: 640
[[640. 109.]
 [ 31.  66.]]


[I 2024-11-18 00:35:54,843] Trial 95 finished with value: 0.788235294117647 and parameters: {'hidden_dim': 485, 'latent_dim': 17, 'beta': 0.5393053569146099, 'gamma': 1.6994818065517363, 'dropout_rate': 0.40289771737142893, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 51
Total False Negatives: 18
Total True Positives: 67
Total True Negatives: 699
[[699.  51.]
 [ 18.  67.]]


[I 2024-11-18 00:37:32,192] Trial 96 finished with value: 0.7790697674418605 and parameters: {'hidden_dim': 472, 'latent_dim': 13, 'beta': 0.6952999333826555, 'gamma': 1.8346923349665447, 'dropout_rate': 0.1563458359058399, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 48
Total False Negatives: 19
Total True Positives: 67
Total True Negatives: 702
[[702.  48.]
 [ 19.  67.]]


[I 2024-11-18 00:39:13,176] Trial 97 finished with value: 0.7444444444444445 and parameters: {'hidden_dim': 503, 'latent_dim': 6, 'beta': 0.7909410961774179, 'gamma': 1.4747374169346226, 'dropout_rate': 0.14129780601693126, 'activation': 'ELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 108
Total False Negatives: 23
Total True Positives: 67
Total True Negatives: 642
[[642. 108.]
 [ 23.  67.]]


[I 2024-11-18 00:40:52,366] Trial 98 finished with value: 0.8271604938271605 and parameters: {'hidden_dim': 448, 'latent_dim': 19, 'beta': 0.5661784512945859, 'gamma': 1.5811822793092523, 'dropout_rate': 0.17797796243728825, 'activation': 'LeakyReLU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 64
Total False Negatives: 14
Total True Positives: 67
Total True Negatives: 686
[[686.  64.]
 [ 14.  67.]]


[I 2024-11-18 00:42:35,146] Trial 99 finished with value: 0.7586206896551724 and parameters: {'hidden_dim': 493, 'latent_dim': 20, 'beta': 0.630860208119373, 'gamma': 1.7402833188337494, 'dropout_rate': 0.10378134967773636, 'activation': 'GELU'}. Best is trial 85 with value: 0.9178082191780822.



=== Summary ===
Total False Positives: 47
Total False Negatives: 21
Total True Positives: 66
Total True Negatives: 703
[[703.  47.]
 [ 21.  66.]]
Best Hyperparameters: {'hidden_dim': 476, 'latent_dim': 16, 'beta': 0.5494693076818475, 'gamma': 1.7424041881705277, 'dropout_rate': 0.10253196823027107, 'activation': 'GELU'}


In [350]:
best_params = {'hidden_dim': 476, 'latent_dim': 16, 'beta': 0.5494693076818475, 'gamma': 1.7424041881705277, 'dropout_rate': 0.10253196823027107, 'activation': 'GELU'}
beta = best_params["beta"]
gamma = best_params["gamma"]
num_epochs = 150

In [360]:
all_false_positives = []
all_false_negatives = []
all_true_positives = []
all_true_negatives = []

num_epochs = 100

n_folds = 5
skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=42)

full_data_tensor = torch.tensor(frb_data_scaled, dtype=torch.float32)
full_labels_tensor = torch.tensor(labels.values, dtype=torch.long)

for fold, (train_index, val_index) in enumerate(skf.split(frb_data_scaled, labels)):
    print(f"\n=== Fold {fold + 1}/{n_folds} ===")
    
    train_data, val_data = frb_data_scaled[train_index], frb_data_scaled[val_index]
    train_labels, val_labels = labels.iloc[train_index], labels.iloc[val_index]
    
    train_tensor = torch.tensor(train_data, dtype=torch.float32)
    val_tensor = torch.tensor(val_data, dtype=torch.float32)
    train_labels_tensor = torch.tensor(train_labels.values, dtype=torch.long)
    val_labels_tensor = torch.tensor(val_labels.values, dtype=torch.long)
    
    train_dataset = TensorDataset(train_tensor, train_labels_tensor)
    val_dataset = TensorDataset(val_tensor, val_labels_tensor)
    
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    
    best_model = SupervisedVAE(
        input_dim, 
        best_params["hidden_dim"], 
        best_params["latent_dim"], 
        best_params["dropout_rate"], 
        activation=get_activation_function(best_params["activation"])
    ).to(device)
    
    optimizer = torch.optim.Adam(best_model.parameters(), lr=1e-3)
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=4)
    
    # Train the model
    for epoch in range(1, num_epochs + 1):
        train_loss, _, _, _, train_accuracy = train_supervised(best_model, optimizer, scheduler, epoch, beta, gamma)
        val_loss, _, _, _, val_accuracy = validate_supervised(best_model, optimizer, scheduler, epoch, beta, gamma)
        scheduler.step(val_loss)
        
        # Early stopping
        if early_stopping([val_loss], patience):
            print(f"Early stopping triggered at epoch {epoch}")
            break

    val_accuracy, val_class_report, val_conf_matrix, val_preds, val_labels = evaluate_classifier_full(best_model, val_loader, device)
    
    print(f"Validation Accuracy: {val_accuracy:.4f}")
    print("Classification Report:\n", val_class_report)
    print("Confusion Matrix:\n", val_conf_matrix)
    
    misclassified_non_repeaters = (val_labels == 0) & (val_preds == 1)
    misclassified_indices = val_index[misclassified_non_repeaters]
    misclassified_sources = original_data.loc[misclassified_indices, "Source"].drop_duplicates()
    
    false_positives_fold = original_data.loc[val_index[(val_labels == 0) & (val_preds == 1)], "Source"]
    false_negatives_fold = original_data.loc[val_index[(val_labels == 1) & (val_preds == 0)], "Source"]
    true_positives_fold = original_data.loc[val_index[(val_labels == 1) & (val_preds == 1)], "Source"]
    true_negatives_fold = original_data.loc[val_index[(val_labels == 0) & (val_preds == 0)], "Source"]
    
    # fold_false_positives = []
    for source in misclassified_sources:
        # fold_false_positives.append(source)
        if source in garcia_list or source in luo_list or source in zhu_ge_list:
            print(f"False positive in fold {fold + 1}: {source}")
            
    all_false_negatives.extend(false_negatives_fold)
    all_true_positives.extend(true_positives_fold)
    all_true_negatives.extend(true_negatives_fold)
    all_false_positives.extend(false_positives_fold)
    
    
all_false_positives = pd.Series(all_false_positives)
all_false_negatives = pd.Series(all_false_negatives)
all_true_positives = pd.Series(all_true_positives)
all_true_negatives = pd.Series(all_true_negatives)

print("\n=== Summary ===")
print(f"Total False Positives: {all_false_positives.nunique()}")
print(f"Total False Negatives: {all_false_negatives.nunique()}")
print(f"Total True Positives: {all_true_positives.nunique()}")
print(f"Total True Negatives: {all_true_negatives.nunique()}")

FP = all_false_positives.nunique()
FN = all_false_negatives.nunique()
TP = all_true_positives.nunique()
TN = all_true_negatives.nunique()

# Confusion matrix

conf_mat_final = np.zeros((2, 2))
conf_mat_final[0, 0] = TN
conf_mat_final[0, 1] = FP
conf_mat_final[1, 0] = FN
conf_mat_final[1, 1] = TP

print(conf_mat_final)

precision = TP / (TP + FP)
accuracy = (TP + TN) / (TP + TN + FP + FN)
recall = TP / (TP + FN)
f1_score = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

print("\n=== Classification Metrics ===")
# print(f"Precision: {precision:.4f}")
print(f"Recall (Sensitivity): {recall:.4f}")
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1_score:.4f}")



=== Fold 1/5 ===
Validation Accuracy: 0.9919
Classification Report:
               precision    recall  f1-score   support

Non-Repeater       0.99      0.95      0.97       238
    Repeater       0.99      1.00      1.00      1495

    accuracy                           0.99      1733
   macro avg       0.99      0.98      0.98      1733
weighted avg       0.99      0.99      0.99      1733

Confusion Matrix:
 [[ 227   11]
 [   3 1492]]
False positive in fold 1: FRB20180928A

=== Fold 2/5 ===
Validation Accuracy: 0.9925
Classification Report:
               precision    recall  f1-score   support

Non-Repeater       0.97      0.97      0.97       238
    Repeater       1.00      1.00      1.00      1495

    accuracy                           0.99      1733
   macro avg       0.99      0.98      0.98      1733
weighted avg       0.99      0.99      0.99      1733

Confusion Matrix:
 [[ 231    7]
 [   6 1489]]
False positive in fold 2: FRB20190418A
False positive in fold 2: FRB2019061

In [361]:
# Evaluation on overall data

FP = len(all_false_positives)
FN = len(all_false_negatives)
TP = len(all_true_positives)
TN = len(all_true_negatives)


precision = TP / (TP + FN)
accuracy = (TP + TN) / (TP + TN + FP + FN)
recall = TP / (TP + FN)
f1_score = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

conf_mat_overall = np.zeros((2, 2))
conf_mat_overall[0, 0] = TN
conf_mat_overall[0, 1] = FP
conf_mat_overall[1, 0] = FN
conf_mat_overall[1, 1] = TP

print(conf_mat_overall)

print("\n=== Classification Metrics Overall ===")
print(f"Precision: {precision:.4f}")
print(f"Recall (Sensitivity): {recall:.4f}")
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1_score:.4f}")


[[1153.   38.]
 [  30. 7443.]]

=== Classification Metrics Overall ===
Precision: 0.9960
Recall (Sensitivity): 0.9960
Accuracy: 0.9922
F1 Score: 0.9960


In [362]:
# Evaluation on unique FRB data

FP = all_false_positives.nunique()
FN = all_false_negatives.nunique()
TP = all_true_positives.nunique()
TN = all_true_negatives.nunique()

# Confusion matrix

conf_mat_final = np.zeros((2, 2))
conf_mat_final[0, 0] = TN
conf_mat_final[0, 1] = FP
conf_mat_final[1, 0] = FN
conf_mat_final[1, 1] = TP

print(conf_mat_final)

precision = TP / (TP + FN)
accuracy = (TP + TN) / (TP + TN + FP + FN)
recall = TP / (TP + FN)
f1_score = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

print("\n=== Classification Metrics ===")
print(f"Precision: {precision:.4f}")
print(f"Recall (Sensitivity): {recall:.4f}")
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1_score:.4f}")

[[719.  30.]
 [ 16.  67.]]

=== Classification Metrics ===
Precision: 0.8072
Recall (Sensitivity): 0.8072
Accuracy: 0.9447
F1 Score: 0.8072


In [363]:
for source in all_false_positives.drop_duplicates():
    if source in garcia_list or source in luo_list or source in zhu_ge_list:
        print(source)

FRB20180928A
FRB20190418A
FRB20190617B
FRB20190206A
